# Use the official Node.js image as a base
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY client/package*.json ./
RUN npm install

# Copy the rest of the client code
COPY client/ .

# Expose port 3000 for the client (or adjust if needed)
EXPOSE 8000

# Start the client
CMD ["npm", "start"]
